<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inchirieri.Core\Inchirieri.Core.csproj" />
    <ProjectReference Include="..\Inchirieri.Data\Inchirieri.Data.csproj" />
  </ItemGroup>
</Project>
